spring:
  application:
    name: contractor-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/contractor-service-db
    username: user
    password: 1

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        jdbc:
          core: DEBUG